"""
Figure generation script for Linear Algebra Chapter 18: Frontiers and Summary.

This is the SERIES FINALE. The figures are designed to (a) recap the 18-chapter
journey as a single coherent picture, and (b) tease the frontier topics where
linear algebra continues to power new science.

Figures
-------
fig1_concept_map        Eighteen-chapter dependency graph drawn with networkx.
                        Nodes coloured by topical band (foundations, structure,
                        decomposition, computation, applications, frontiers);
                        edges show which earlier chapter each later chapter
                        builds on. The single image you can show after the
                        whole journey is finished.

fig2_quantum_computing  Quantum-computing primer in one panel:
                        (a) the Bloch sphere with several states marked;
                        (b) action of the Hadamard gate on |0>;
                        (c) a small Bell-state circuit and its 4-vector
                        amplitudes after H tensor I and after CNOT.

fig3_tensor_networks    Diagrammatic comparison of three tensor networks --
                        Matrix Product State (MPS / Tensor Train), a generic
                        Tensor Network with loops, and a MERA layered network.
                        Drawn with networkx + custom node placement; the
                        message is "open legs are physical indices, contracted
                        legs are bond dimensions".

fig4_lie_rotations      The matrix exponential as a one-parameter subgroup:
                        e^(theta K) traces a great-circle rotation on the
                        sphere. We show three orbits generated by Lx, Ly, Lz
                        (the so(3) basis) starting from a common point. The
                        infinitesimal generator (a tangent arrow) is drawn at
                        each starting point.

fig5_random_to_free     Two halves of one figure: left is the Marchenko-Pastur
                        bulk for a sample covariance (classical RMT); right
                        is the free additive convolution of two semicircles
                        producing a wider semicircle. The bridge between the
                        two: free probability gives the calculus that links
                        independent random matrices.

fig6_persistence        Topological data analysis preview: a noisy point cloud
                        sampled from an annulus on the left, and its
                        persistence diagram (H0 + H1) on the right. One
                        long-lived H1 point (the loop) sits well above the
                        diagonal; short-lived points hug it.

fig7_three_pillars      The book's recurring triangle: Geometry / Numerics /
                        Computation. Each vertex carries representative
                        artefacts from the series (Bloch sphere; condition
                        number; sparse-matrix kernel). The interior shows
                        SVD as the meeting point that all three perspectives
                        agree on.

Style
-----
matplotlib seaborn-v0_8-whitegrid, dpi=150.
Palette: #2563eb blue (primary), #7c3aed purple, #10b981 green, #f59e0b amber.

Output
------
PNGs are written to BOTH the EN and ZH article asset folders so the markdown
references stay consistent across languages.

Usage
-----
    python3 scripts/figures/linear-algebra/18-frontiers-and-summary.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from matplotlib.patches import FancyArrowPatch
from mpl_toolkits.mplot3d import proj3d  # noqa: F401  (registers 3d projection)

import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _style import setup_style, COLORS, annotate_callout  # noqa: E402, F401
setup_style()



# ---------------------------------------------------------------------------
# Style
# ---------------------------------------------------------------------------
# style applied via _style.setup_style()

C_BLUE = COLORS["primary"]
C_PURPLE = COLORS["accent"]
C_GREEN = COLORS["success"]
C_AMBER = COLORS["warning"]
C_GRAY = COLORS["muted"]
C_DARK = COLORS["text"]
C_LIGHT = COLORS["grid"]
C_RED = COLORS["danger"]

DPI = 150
RNG = np.random.default_rng(20240430)

EN_DIR = Path(
    "/Users/kchen/Desktop/Project/chenk-site/source/_posts/en/linear-algebra/"
    "18-frontiers-and-summary"
)
ZH_DIR = Path(
    "/Users/kchen/Desktop/Project/chenk-site/source/_posts/zh/linear-algebra/"
    "18-前沿应用与总结"
)


def save(fig: plt.Figure, name: str) -> None:
    """Save the figure to BOTH EN and ZH asset folders as <name>.png."""
    EN_DIR.mkdir(parents=True, exist_ok=True)
    ZH_DIR.mkdir(parents=True, exist_ok=True)
    for d in (EN_DIR, ZH_DIR):
        path = d / f"{name}.png"
        fig.savefig(path, dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Figure 1: 18-chapter concept map (dependency graph)
# ---------------------------------------------------------------------------
def fig1_concept_map() -> None:
    chapters = [
        # (id, label, band, x, y)
        (1,  "1\nVectors",             "foundation",   0.0,  4.0),
        (2,  "2\nVector spaces",       "foundation",   1.6,  4.0),
        (3,  "3\nLinear maps",         "foundation",   3.2,  4.0),
        (4,  "4\nDeterminants",        "structure",    4.8,  4.0),
        (5,  "5\nLinear systems",      "structure",    1.6,  2.7),
        (6,  "6\nEigenvalues",         "structure",    3.2,  2.7),
        (7,  "7\nOrthogonality",       "structure",    4.8,  2.7),
        (8,  "8\nSymmetric / spectral","decomposition",3.2,  1.4),
        (9,  "9\nSVD",                 "decomposition",4.8,  1.4),
        (10, "10\nNorms / cond. #",    "computation",  6.4,  2.7),
        (11, "11\nMatrix calculus",    "computation",  6.4,  4.0),
        (12, "12\nSparsity / CS",      "computation",  6.4,  1.4),
        (13, "13\nTensors",            "computation",  4.8,  0.1),
        (14, "14\nRandom matrices",    "computation",  6.4,  0.1),
        (15, "15\nML",                 "applications", 8.0,  3.4),
        (16, "16\nDeep learning",      "applications", 8.0,  2.1),
        (17, "17\nVision",             "applications", 8.0,  0.8),
        (18, "18\nFrontiers",          "frontier",     9.6,  2.1),
    ]

    band_color = {
        "foundation":    C_BLUE,
        "structure":     C_PURPLE,
        "decomposition": C_GREEN,
        "computation":   C_AMBER,
        "applications":  C_RED,
        "frontier":      C_DARK,
    }
    band_label = {
        "foundation":    "Foundations (1-3)",
        "structure":     "Structure (4-7)",
        "decomposition": "Decompositions (8-9)",
        "computation":   "Computation (10-14)",
        "applications":  "Applications (15-17)",
        "frontier":      "Frontier (18)",
    }

    edges = [
        (1, 2), (2, 3), (3, 4), (3, 5), (5, 6), (3, 6),
        (2, 7), (6, 8), (7, 8), (8, 9), (6, 9),
        (3, 11), (7, 10), (9, 10), (5, 12), (7, 12),
        (9, 13), (3, 13), (9, 14), (6, 14),
        (9, 15), (11, 15), (14, 15),
        (11, 16), (15, 16), (9, 16),
        (9, 17), (3, 17), (16, 17),
        (16, 18), (15, 18), (17, 18), (9, 18), (8, 18),
    ]

    G = nx.DiGraph()
    pos = {}
    color = {}
    for cid, label, band, x, y in chapters:
        G.add_node(cid, label=label)
        pos[cid] = (x, y)
        color[cid] = band_color[band]
    G.add_edges_from(edges)

    fig, ax = plt.subplots(figsize=(13.5, 7.0))

    # Edges first (curved, soft).
    for u, v in G.edges():
        x1, y1 = pos[u]
        x2, y2 = pos[v]
        arrow = FancyArrowPatch(
            (x1, y1), (x2, y2),
            arrowstyle="-|>", mutation_scale=8,
            color=C_GRAY, alpha=0.55, lw=1.0,
            connectionstyle="arc3,rad=0.07",
            shrinkA=18, shrinkB=18,
        )
        ax.add_patch(arrow)

    # Nodes as coloured rounded boxes.
    for cid, label, band, x, y in chapters:
        ax.scatter(x, y, s=2400, color=color[cid], alpha=0.90,
                   edgecolors="white", linewidths=2, zorder=3)
        ax.text(x, y, label, ha="center", va="center",
                fontsize=8.5, color="white", fontweight="bold", zorder=4)

    # Legend by band.
    handles = [
        mpatches.Patch(color=band_color[b], label=band_label[b])
        for b in ["foundation", "structure", "decomposition",
                  "computation", "applications", "frontier"]
    ]
    ax.legend(handles=handles, loc="lower left", ncol=3,
              framealpha=0.95, fontsize=9)

    ax.set_xlim(-0.9, 10.6)
    ax.set_ylim(-0.7, 4.9)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_title(
        "Linear algebra: an 18-chapter dependency graph",
        fontsize=14, color=C_DARK, pad=10,
    )
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.grid(False)

    save(fig, "fig1_concept_map")


# ---------------------------------------------------------------------------
# Figure 2: Quantum computing in one figure
# ---------------------------------------------------------------------------
def _draw_bloch(ax) -> None:
    """Draw a Bloch sphere with several marked states on a 3D axis."""
    u = np.linspace(0, 2 * np.pi, 60)
    v = np.linspace(0, np.pi, 30)
    xs = np.outer(np.cos(u), np.sin(v))
    ys = np.outer(np.sin(u), np.sin(v))
    zs = np.outer(np.ones_like(u), np.cos(v))
    ax.plot_surface(xs, ys, zs, color=C_BLUE, alpha=0.10,
                    linewidth=0, antialiased=True)

    # Equator and meridians.
    theta = np.linspace(0, 2 * np.pi, 200)
    ax.plot(np.cos(theta), np.sin(theta), 0, color=C_GRAY, lw=0.8, alpha=0.7)
    ax.plot(np.cos(theta), 0 * theta, np.sin(theta), color=C_GRAY,
            lw=0.8, alpha=0.7)
    ax.plot(0 * theta, np.cos(theta), np.sin(theta), color=C_GRAY,
            lw=0.8, alpha=0.7)

    # Axes.
    for vec, color in [((1.2, 0, 0), C_GRAY),
                       ((0, 1.2, 0), C_GRAY),
                       ((0, 0, 1.2), C_GRAY)]:
        ax.plot([0, vec[0]], [0, vec[1]], [0, vec[2]],
                color=color, lw=1.0, alpha=0.7)

    # States: |0>, |1>, |+>, |->, plus arbitrary.
    states = [
        ((0, 0, 1),     "|0>",       C_BLUE),
        ((0, 0, -1),    "|1>",       C_PURPLE),
        ((1, 0, 0),     "|+>",       C_GREEN),
        ((-1, 0, 0),    "|->",       C_AMBER),
        ((0, 1, 0),     "|i>",       C_RED),
    ]
    for (x, y, z), label, c in states:
        ax.quiver(0, 0, 0, x, y, z, color=c, lw=2.0, arrow_length_ratio=0.10)
        ax.text(1.18 * x, 1.18 * y, 1.18 * z, label,
                color=c, fontsize=9, fontweight="bold")

    ax.set_xlim(-1.2, 1.2)
    ax.set_ylim(-1.2, 1.2)
    ax.set_zlim(-1.2, 1.2)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])
    ax.set_box_aspect([1, 1, 1])
    ax.set_title("(a) Bloch sphere: a qubit is a unit vector",
                 fontsize=10.5, color=C_DARK, pad=2)


def _draw_hadamard_action(ax) -> None:
    """Bar chart of |0> -> H -> (|0> + |1>) / sqrt(2)."""
    states = ["|0>", "|1>"]
    before = np.array([1.0, 0.0])
    after = np.array([1 / np.sqrt(2), 1 / np.sqrt(2)])

    x = np.arange(2)
    w = 0.36
    ax.bar(x - w / 2, before, width=w, color=C_BLUE, alpha=0.85,
           edgecolor="white", label="Before: |0>")
    ax.bar(x + w / 2, after, width=w, color=C_GREEN, alpha=0.85,
           edgecolor="white", label="After: H|0>")

    for xi, val in zip(x - w / 2, before):
        ax.text(xi, val + 0.02, f"{val:.2f}", ha="center",
                fontsize=8.5, color=C_DARK)
    for xi, val in zip(x + w / 2, after):
        ax.text(xi, val + 0.02, f"{val:.2f}", ha="center",
                fontsize=8.5, color=C_DARK)

    ax.set_xticks(x)
    ax.set_xticklabels(states, fontsize=10)
    ax.set_ylabel("Amplitude")
    ax.set_ylim(0, 1.15)
    ax.set_title("(b) Hadamard gate creates superposition",
                 fontsize=10.5, color=C_DARK)
    ax.legend(loc="upper right", fontsize=8.5)


def _draw_bell_circuit(ax) -> None:
    """Schematic Bell-state circuit and the resulting 4-vector amplitudes."""
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_title("(c) Bell state: |00> -> H tensor I -> CNOT", fontsize=10.5,
                 color=C_DARK)

    # Two qubit wires.
    ax.plot([0.5, 6.5], [4.5, 4.5], color=C_DARK, lw=1.4)
    ax.plot([0.5, 6.5], [3.0, 3.0], color=C_DARK, lw=1.4)
    ax.text(0.1, 4.5, "|0>", fontsize=10, va="center", color=C_DARK)
    ax.text(0.1, 3.0, "|0>", fontsize=10, va="center", color=C_DARK)

    # H gate.
    ax.add_patch(mpatches.Rectangle((1.6, 4.1), 0.8, 0.8,
                                    facecolor=C_BLUE, edgecolor=C_DARK))
    ax.text(2.0, 4.5, "H", color="white", ha="center", va="center",
            fontsize=11, fontweight="bold")

    # CNOT (control + target).
    ax.scatter([4.0], [4.5], color=C_DARK, s=60, zorder=5)
    ax.plot([4.0, 4.0], [3.0, 4.5], color=C_DARK, lw=1.2)
    circ = mpatches.Circle((4.0, 3.0), 0.30, fill=False,
                           edgecolor=C_DARK, lw=1.4)
    ax.add_patch(circ)
    ax.plot([3.7, 4.3], [3.0, 3.0], color=C_DARK, lw=1.2)
    ax.plot([4.0, 4.0], [2.7, 3.3], color=C_DARK, lw=1.2)

    ax.text(2.0, 5.4, "create\nsuperposition", ha="center",
            fontsize=8.5, color=C_BLUE)
    ax.text(4.0, 5.4, "entangle", ha="center",
            fontsize=8.5, color=C_PURPLE)

    # Amplitudes table on the right.
    labels = ["|00>", "|01>", "|10>", "|11>"]
    after_h = [1 / np.sqrt(2), 0, 1 / np.sqrt(2), 0]
    after_cnot = [1 / np.sqrt(2), 0, 0, 1 / np.sqrt(2)]
    base_x = 7.0
    col1_x = base_x + 0.40
    col2_x = base_x + 1.95
    ax.text(col1_x, 5.55, "after H$\\otimes$I", fontsize=8.5,
            color=C_BLUE, ha="left")
    ax.text(col2_x, 5.55, "after CNOT", fontsize=8.5,
            color=C_PURPLE, ha="left")
    for i, lab in enumerate(labels):
        y = 4.8 - 0.55 * i
        ax.text(base_x - 0.2, y, lab, fontsize=9, color=C_DARK, va="center")
        # bar1
        v1 = after_h[i]
        ax.add_patch(mpatches.Rectangle(
            (col1_x, y - 0.16), 0.55 * v1, 0.32,
            facecolor=C_BLUE, alpha=0.75, edgecolor="white"))
        ax.text(col1_x + 0.55 * v1 + 0.05, y, f"{v1:.2f}",
                fontsize=8, color=C_DARK, va="center")
        # bar2
        v2 = after_cnot[i]
        ax.add_patch(mpatches.Rectangle(
            (col2_x, y - 0.16), 0.55 * v2, 0.32,
            facecolor=C_PURPLE, alpha=0.75, edgecolor="white"))
        ax.text(col2_x + 0.55 * v2 + 0.05, y, f"{v2:.2f}",
                fontsize=8, color=C_DARK, va="center")

    ax.text(5.5, 1.0, r"$|\Phi^+\rangle = (|00\rangle + |11\rangle)/\sqrt{2}$",
            fontsize=11, color=C_DARK, ha="center")
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.grid(False)


def fig2_quantum_computing() -> None:
    fig = plt.figure(figsize=(13.5, 5.0))
    ax1 = fig.add_subplot(1, 3, 1, projection="3d")
    ax2 = fig.add_subplot(1, 3, 2)
    ax3 = fig.add_subplot(1, 3, 3)
    _draw_bloch(ax1)
    _draw_hadamard_action(ax2)
    _draw_bell_circuit(ax3)
    fig.suptitle("Quantum computing in linear algebra: state, gate, entanglement",
                 fontsize=13, color=C_DARK)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    save(fig, "fig2_quantum_computing")


# ---------------------------------------------------------------------------
# Figure 3: Tensor network diagrams (MPS / general TN / MERA)
# ---------------------------------------------------------------------------
def _circle(ax, x, y, r=0.18, color=C_BLUE):
    ax.add_patch(mpatches.Circle((x, y), r, facecolor=color,
                                 edgecolor=C_DARK, lw=1.0, zorder=3))


def _draw_mps(ax) -> None:
    ax.set_title("(a) Matrix Product State (Tensor Train)",
                 fontsize=10.5, color=C_DARK)
    n = 6
    xs = np.linspace(0.5, 5.5, n)
    y = 1.8
    for i, x in enumerate(xs):
        _circle(ax, x, y, color=C_BLUE)
        ax.text(x, y, f"$G_{i+1}$", color="white", fontsize=8.5,
                ha="center", va="center", fontweight="bold")
        # physical leg downward
        ax.plot([x, x], [y - 0.18, y - 0.7], color=C_DARK, lw=1.2)
        ax.text(x, y - 0.85, f"$i_{i+1}$", ha="center", fontsize=8.5,
                color=C_DARK)
    # bond legs
    for i in range(n - 1):
        ax.plot([xs[i] + 0.18, xs[i+1] - 0.18], [y, y], color=C_GRAY, lw=1.4)
    ax.text(3.0, 2.9,
            r"$\mathcal{X}(i_1,\ldots,i_N)=G_1(i_1)\,G_2(i_2)\cdots G_N(i_N)$",
            ha="center", fontsize=10, color=C_DARK)
    ax.text(3.0, 0.25, "open legs = physical indices, lines = bond dims",
            ha="center", fontsize=8.5, color=C_GRAY)
    ax.set_xlim(0, 6)
    ax.set_ylim(0, 3.4)
    ax.set_xticks([]); ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)
    ax.grid(False)


def _draw_general_tn(ax) -> None:
    ax.set_title("(b) Tensor Network with loops",
                 fontsize=10.5, color=C_DARK)
    pts = {
        "A": (1.2, 2.6), "B": (2.6, 2.6), "C": (4.0, 2.6),
        "D": (1.9, 1.4), "E": (3.3, 1.4),
    }
    edges = [("A", "B"), ("B", "C"), ("A", "D"), ("D", "E"),
             ("E", "C"), ("D", "B"), ("E", "B")]
    for u, v in edges:
        x1, y1 = pts[u]; x2, y2 = pts[v]
        ax.plot([x1, x2], [y1, y2], color=C_GRAY, lw=1.4)
    # open legs
    open_legs = {"A": (-1, 0), "C": (1, 0), "D": (-0.4, -1), "E": (0.4, -1)}
    for k, (dx, dy) in open_legs.items():
        x, y = pts[k]
        nx_, ny_ = x + 0.7 * dx, y + 0.7 * dy
        ax.plot([x, nx_], [y, ny_], color=C_DARK, lw=1.2)
    for label, (x, y) in pts.items():
        _circle(ax, x, y, color=C_PURPLE)
        ax.text(x, y, label, color="white", fontsize=8.5,
                ha="center", va="center", fontweight="bold")
    ax.text(2.6, 0.25, "loops carry correlations across the lattice",
            ha="center", fontsize=8.5, color=C_GRAY)
    ax.set_xlim(0, 5.2)
    ax.set_ylim(0, 3.4)
    ax.set_xticks([]); ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)
    ax.grid(False)


def _draw_mera(ax) -> None:
    ax.set_title("(c) MERA: layered, multi-scale",
                 fontsize=10.5, color=C_DARK)
    # Bottom layer (physical sites).
    n = 8
    xs = np.linspace(0.5, 5.5, n)
    y0 = 0.6
    for x in xs:
        _circle(ax, x, y0, r=0.13, color=C_GREEN)
        ax.plot([x, x], [y0 - 0.13, y0 - 0.4], color=C_DARK, lw=1.0)
    # Disentanglers (purple) layer.
    y1 = 1.4
    dx_pairs = [(xs[i], xs[i+1]) for i in (0, 2, 4, 6)]
    for x1, x2 in dx_pairs:
        cx = (x1 + x2) / 2
        ax.add_patch(mpatches.Rectangle((cx - 0.22, y1 - 0.12),
                                        0.44, 0.24,
                                        facecolor=C_PURPLE,
                                        edgecolor=C_DARK, lw=1.0))
        ax.plot([x1, cx - 0.10], [y0 + 0.13, y1 - 0.12], color=C_GRAY, lw=1.0)
        ax.plot([x2, cx + 0.10], [y0 + 0.13, y1 - 0.12], color=C_GRAY, lw=1.0)
    # Isometries (blue) higher layer: shift by one site.
    y2 = 2.2
    iso_pairs = [(xs[1], xs[2]), (xs[3], xs[4]), (xs[5], xs[6])]
    for x1, x2 in iso_pairs:
        cx = (x1 + x2) / 2
        ax.add_patch(mpatches.Circle((cx, y2), 0.18,
                                     facecolor=C_BLUE,
                                     edgecolor=C_DARK, lw=1.0))
        ax.plot([x1, cx - 0.13], [y1 + 0.12, y2 - 0.13], color=C_GRAY, lw=1.0)
        ax.plot([x2, cx + 0.13], [y1 + 0.12, y2 - 0.13], color=C_GRAY, lw=1.0)
    # Top layer.
    y3 = 3.0
    top_xs = [(iso_pairs[i][0] + iso_pairs[i][1]) / 2 for i in range(3)]
    for x in top_xs:
        ax.plot([x, x], [y2 + 0.18, y3], color=C_GRAY, lw=1.0)
    ax.text(3.0, y3 + 0.05, "coarse-grained scale",
            ha="center", fontsize=8.5, color=C_DARK)

    # Legend
    legend = [
        mpatches.Patch(color=C_GREEN, label="physical sites"),
        mpatches.Patch(color=C_PURPLE, label="disentanglers"),
        mpatches.Patch(color=C_BLUE, label="isometries"),
    ]
    ax.legend(handles=legend, loc="upper left", fontsize=8, framealpha=0.95)
    ax.set_xlim(-0.2, 6.2)
    ax.set_ylim(0, 3.6)
    ax.set_xticks([]); ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)
    ax.grid(False)


def fig3_tensor_networks() -> None:
    fig, axes = plt.subplots(1, 3, figsize=(14.0, 4.4))
    _draw_mps(axes[0])
    _draw_general_tn(axes[1])
    _draw_mera(axes[2])
    fig.suptitle("Tensor networks: graphical calculus for high-dimensional tensors",
                 fontsize=13, color=C_DARK)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    save(fig, "fig3_tensor_networks")


# ---------------------------------------------------------------------------
# Figure 4: Matrix exponential as Lie-group rotations on the sphere
# ---------------------------------------------------------------------------
def _so3_basis():
    Lx = np.array([[0, 0, 0], [0, 0, -1], [0, 1, 0]], dtype=float)
    Ly = np.array([[0, 0, 1], [0, 0, 0], [-1, 0, 0]], dtype=float)
    Lz = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 0]], dtype=float)
    return Lx, Ly, Lz


def _expm_skew(K: np.ndarray, theta: float) -> np.ndarray:
    """Closed form for the exponential of a 3x3 skew matrix (Rodrigues)."""
    # Identify axis from skew matrix.
    w = np.array([K[2, 1], K[0, 2], K[1, 0]])
    n = np.linalg.norm(w)
    if n < 1e-12:
        return np.eye(3)
    k = w / n
    K_hat = np.array([[0, -k[2], k[1]],
                      [k[2], 0, -k[0]],
                      [-k[1], k[0], 0]])
    return (np.eye(3)
            + np.sin(theta * n) * K_hat
            + (1 - np.cos(theta * n)) * (K_hat @ K_hat))


def fig4_lie_rotations() -> None:
    Lx, Ly, Lz = _so3_basis()
    p0 = np.array([1.0, 0.0, 0.0]) / np.sqrt(1.0)  # start point on sphere
    p0 = p0 / np.linalg.norm(p0)
    # Pick a non-axis-aligned starting point so all three orbits look different.
    p0 = np.array([0.7, 0.5, 0.5])
    p0 = p0 / np.linalg.norm(p0)

    thetas = np.linspace(0, 2 * np.pi, 200)

    fig = plt.figure(figsize=(9.5, 7.2))
    ax = fig.add_subplot(111, projection="3d")

    # Sphere surface.
    u = np.linspace(0, 2 * np.pi, 60)
    v = np.linspace(0, np.pi, 30)
    xs = np.outer(np.cos(u), np.sin(v))
    ys = np.outer(np.sin(u), np.sin(v))
    zs = np.outer(np.ones_like(u), np.cos(v))
    ax.plot_surface(xs, ys, zs, color=C_GRAY, alpha=0.10,
                    linewidth=0, antialiased=True)

    # Axes.
    for vec in [(1.3, 0, 0), (0, 1.3, 0), (0, 0, 1.3)]:
        ax.plot([0, vec[0]], [0, vec[1]], [0, vec[2]],
                color=C_GRAY, lw=0.8, alpha=0.7)
    ax.text(1.4, 0, 0, "x", color=C_GRAY, fontsize=10)
    ax.text(0, 1.4, 0, "y", color=C_GRAY, fontsize=10)
    ax.text(0, 0, 1.4, "z", color=C_GRAY, fontsize=10)

    orbits = [
        ("$e^{\\theta L_x}$", Lx, C_BLUE),
        ("$e^{\\theta L_y}$", Ly, C_GREEN),
        ("$e^{\\theta L_z}$", Lz, C_AMBER),
    ]

    for label, K, c in orbits:
        pts = np.array([_expm_skew(K, t) @ p0 for t in thetas])
        ax.plot(pts[:, 0], pts[:, 1], pts[:, 2],
                color=c, lw=2.4, label=label)

    # Tangent generators at p0: K p0 for each generator.
    for label, K, c in orbits:
        tan = K @ p0
        tan = tan / (np.linalg.norm(tan) + 1e-12) * 0.45
        ax.quiver(p0[0], p0[1], p0[2],
                  tan[0], tan[1], tan[2],
                  color=c, lw=1.6, arrow_length_ratio=0.25)

    # Starting point.
    ax.scatter(*p0, color=C_DARK, s=60, zorder=5)
    ax.text(p0[0] + 0.06, p0[1] + 0.06, p0[2] + 0.06, "$p_0$",
            color=C_DARK, fontsize=11)

    ax.set_xlim(-1.2, 1.2)
    ax.set_ylim(-1.2, 1.2)
    ax.set_zlim(-1.2, 1.2)
    ax.set_xticks([]); ax.set_yticks([]); ax.set_zticks([])
    ax.set_box_aspect([1, 1, 1])
    ax.legend(loc="upper left", fontsize=10, framealpha=0.95)
    ax.set_title(
        "Matrix exponential of so(3) generators traces great circles on $S^2$",
        fontsize=12, color=C_DARK,
    )
    save(fig, "fig4_lie_rotations")


# ---------------------------------------------------------------------------
# Figure 5: Random matrices to free probability
# ---------------------------------------------------------------------------
def _mp_density(x: np.ndarray, gamma: float) -> np.ndarray:
    lam_minus = (1 - np.sqrt(gamma)) ** 2
    lam_plus = (1 + np.sqrt(gamma)) ** 2
    inside = (x > lam_minus) & (x < lam_plus)
    out = np.zeros_like(x)
    out[inside] = np.sqrt(
        np.maximum((lam_plus - x[inside]) * (x[inside] - lam_minus), 0)
    ) / (2 * np.pi * gamma * x[inside])
    return out


def fig5_random_to_free() -> None:
    fig, axes = plt.subplots(1, 2, figsize=(13.0, 5.0))

    # --- left: Marchenko-Pastur bulk ---
    n, p = 1500, 600
    gamma = p / n
    x = RNG.standard_normal((n, p))
    s = x.T @ x / n
    eigs = np.linalg.eigvalsh(s)

    ax = axes[0]
    ax.hist(eigs, bins=70, density=True, color=C_BLUE, alpha=0.55,
            edgecolor="white", linewidth=0.4, label="Sample covariance eigenvalues")
    xs = np.linspace((1 - np.sqrt(gamma)) ** 2 + 1e-3,
                     (1 + np.sqrt(gamma)) ** 2 - 1e-3, 500)
    ax.plot(xs, _mp_density(xs, gamma), color=C_GREEN, lw=2.4,
            label="Marchenko-Pastur density")
    ax.set_xlabel("Eigenvalue $\\lambda$")
    ax.set_ylabel("Density")
    ax.set_title(rf"Classical RMT: MP bulk at $\gamma=p/n={gamma:.2f}$",
                 fontsize=11.5, color=C_DARK)
    ax.legend(loc="upper right", fontsize=9, framealpha=0.95)

    # --- right: free additive convolution ---
    n2 = 1500
    a1 = RNG.standard_normal((n2, n2))
    w1 = (a1 + a1.T) / np.sqrt(2 * n2)
    a2 = RNG.standard_normal((n2, n2))
    w2 = 0.7 * (a2 + a2.T) / np.sqrt(2 * n2)

    eigs1 = np.linalg.eigvalsh(w1)
    eigs2 = np.linalg.eigvalsh(w2)
    eigs_sum = np.linalg.eigvalsh(w1 + w2)

    ax = axes[1]
    ax.hist(eigs1, bins=70, density=True, color=C_BLUE, alpha=0.40,
            label=r"$W_1$ semicircle")
    ax.hist(eigs2, bins=70, density=True, color=C_PURPLE, alpha=0.40,
            label=r"$W_2 = 0.7\,W'$ semicircle")
    ax.hist(eigs_sum, bins=70, density=True, color=C_AMBER, alpha=0.55,
            label=r"$W_1 + W_2$")
    sigma_sum = np.sqrt(1.0 + 0.7 ** 2)
    radius = 2 * sigma_sum
    xs = np.linspace(-radius, radius, 500)
    ys = (2 / (np.pi * radius ** 2)) * np.sqrt(
        np.maximum(radius ** 2 - xs ** 2, 0))
    ax.plot(xs, ys, color=C_GREEN, lw=2.4,
            label=r"Free CLT: semicircle of radius $2\sqrt{1.49}$")
    ax.set_xlabel("Eigenvalue $\\lambda$")
    ax.set_ylabel("Density")
    ax.set_title("Free probability: independent randomness adds variances",
                 fontsize=11.5, color=C_DARK)
    ax.legend(loc="upper right", fontsize=8.5, framealpha=0.95)

    fig.suptitle("From random matrices (ch. 14) to free probability",
                 fontsize=13, color=C_DARK)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    save(fig, "fig5_random_to_free")


# ---------------------------------------------------------------------------
# Figure 6: Topological data analysis preview
# ---------------------------------------------------------------------------
def _vietoris_rips_h0_h1(points: np.ndarray):
    """Compute persistence diagrams for H0 and H1 using a simple
    Vietoris-Rips style approach that does not require external libraries.

    H0: classical single-linkage merge tree (births at radius 0, deaths when
        components merge).
    H1: detect the dominant 1-cycle by tracking the smallest cycle that
        forms as the radius grows. Returns a single approximate (birth, death)
        for the most persistent loop. This is a rough but adequate sketch
        for visualisation; the long-lived point will sit far above the
        diagonal for an annulus point cloud.
    """
    n = points.shape[0]
    # Pairwise distances.
    diff = points[:, None, :] - points[None, :, :]
    dist = np.sqrt((diff ** 2).sum(-1))

    # H0: Kruskal/union-find on edges in increasing order.
    parent = list(range(n))

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    iu, ju = np.triu_indices(n, k=1)
    edges = sorted(zip(dist[iu, ju], iu, ju))
    h0 = []  # (birth=0, death=eps)
    n_components = n
    for d, i, j in edges:
        ri, rj = find(i), find(j)
        if ri != rj:
            parent[ri] = rj
            h0.append((0.0, d))
            n_components -= 1
        if n_components == 1:
            break
    # The very last component never dies; drop it from the diagram (or set
    # death = max edge as a finite proxy).
    h0 = h0[:-1] if h0 else h0

    # H1: detect when a 1-cycle first appears. For a Vietoris-Rips complex on
    # an annulus, the dominant 1-cycle's birth radius is roughly the largest
    # gap on the inner boundary; its death is roughly the inner radius.
    # We approximate: birth = first edge that closes a cycle when added to
    # the MST; death = radius at which the inner hole gets filled (estimated
    # as 2 * inner_radius).
    parent = list(range(n))
    cycle_births = []
    for d, i, j in edges:
        ri, rj = find(i), find(j)
        if ri == rj:
            cycle_births.append(d)
        else:
            parent[ri] = rj
    # Take the smallest cycle birth as the dominant H1 birth.
    if cycle_births:
        h1_birth = min(cycle_births)
        # Death heuristic: when balls of radius r/2 cover the hole. For a
        # unit-ish annulus we use the inner radius times sqrt(3).
        center = points.mean(axis=0)
        radii = np.sqrt(((points - center) ** 2).sum(-1))
        inner_r = radii.min()
        h1_death = max(h1_birth + 0.05, np.sqrt(3) * inner_r)
        h1 = [(h1_birth, h1_death)]
    else:
        h1 = []

    return np.array(h0), np.array(h1)


def fig6_persistence() -> None:
    # Sample a noisy annulus.
    n = 80
    angles = RNG.uniform(0, 2 * np.pi, n)
    radii = RNG.uniform(0.85, 1.15, n)
    pts = np.column_stack([radii * np.cos(angles),
                           radii * np.sin(angles)])
    pts += 0.04 * RNG.standard_normal(pts.shape)

    h0, h1 = _vietoris_rips_h0_h1(pts)

    fig, axes = plt.subplots(1, 2, figsize=(12.0, 5.2))

    ax = axes[0]
    ax.scatter(pts[:, 0], pts[:, 1], color=C_BLUE, s=24, alpha=0.85,
               edgecolor="white")
    theta = np.linspace(0, 2 * np.pi, 200)
    ax.plot(np.cos(theta), np.sin(theta),
            color=C_GRAY, lw=1.0, linestyle="--", alpha=0.7)
    ax.set_aspect("equal")
    ax.set_xlim(-1.6, 1.6)
    ax.set_ylim(-1.6, 1.6)
    ax.set_title("Point cloud sampled from a noisy annulus",
                 fontsize=11.5, color=C_DARK)
    ax.set_xlabel("$x$"); ax.set_ylabel("$y$")

    ax = axes[1]
    max_r = max(h0[:, 1].max() if len(h0) else 1.0,
                h1[:, 1].max() if len(h1) else 1.0)
    max_r = max_r * 1.15
    ax.plot([0, max_r], [0, max_r], color=C_GRAY, lw=1.0, alpha=0.6)
    if len(h0):
        ax.scatter(h0[:, 0], h0[:, 1], color=C_BLUE, s=30, alpha=0.85,
                   label=r"$H_0$ (components)")
    if len(h1):
        ax.scatter(h1[:, 0], h1[:, 1], color=C_AMBER, s=110, alpha=0.95,
                   marker="D", edgecolor=C_DARK,
                   label=r"$H_1$ (loop)")
        bx, by = h1[0]
        ax.annotate(
            "the loop:\nlong life = real feature",
            xy=(bx, by), xytext=(bx + 0.25, by - 0.30),
            fontsize=9, color=C_DARK,
            arrowprops=dict(arrowstyle="->", color=C_DARK, lw=1.0),
        )
    ax.set_xlim(0, max_r)
    ax.set_ylim(0, max_r)
    ax.set_xlabel("Birth scale")
    ax.set_ylabel("Death scale")
    ax.set_title("Persistence diagram",
                 fontsize=11.5, color=C_DARK)
    ax.legend(loc="lower right", fontsize=9, framealpha=0.95)

    fig.suptitle("Topological data analysis: shape persists across scales",
                 fontsize=13, color=C_DARK)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    save(fig, "fig6_persistence")


# ---------------------------------------------------------------------------
# Figure 7: The recurring triangle -- Geometry, Numerics, Computation
# ---------------------------------------------------------------------------
def fig7_three_pillars() -> None:
    fig, ax = plt.subplots(figsize=(10.0, 8.0))

    # Triangle vertices.
    A = np.array([5.0, 8.4])    # top: Geometry
    B = np.array([0.8, 1.2])    # bottom-left: Numerics
    C = np.array([9.2, 1.2])    # bottom-right: Computation

    tri = mpatches.Polygon([A, B, C], closed=True,
                           facecolor=C_LIGHT, alpha=0.30,
                           edgecolor=C_DARK, lw=1.4)
    ax.add_patch(tri)

    # Centroid: SVD as the meeting point.
    centroid = (A + B + C) / 3.0
    ax.add_patch(mpatches.Circle(centroid, 0.55,
                                 facecolor=C_GREEN, edgecolor=C_DARK, lw=1.4))
    ax.text(centroid[0], centroid[1], "SVD",
            ha="center", va="center", fontsize=13,
            color="white", fontweight="bold")
    ax.text(centroid[0], centroid[1] - 0.95,
            "the one decomposition\nthe three pillars agree on",
            ha="center", fontsize=8.5, color=C_DARK)

    # Vertex labels and example artefacts.
    pillars = [
        (A, C_BLUE, "Geometry",
         "vectors, projections,\neigenframes, rotations,\nBloch sphere"),
        (B, C_PURPLE, "Numerics",
         "norms, conditioning,\nstable algorithms,\nfloating point"),
        (C, C_AMBER, "Computation",
         "sparse kernels,\nrandomised methods,\nGPU tensor cores"),
    ]
    for (pos, color, name, body) in pillars:
        ax.add_patch(mpatches.Circle(pos, 0.85,
                                     facecolor=color, edgecolor=C_DARK,
                                     lw=1.6, alpha=0.95))
        ax.text(pos[0], pos[1], name,
                ha="center", va="center", fontsize=12,
                color="white", fontweight="bold")
        # Body text outside the circle, in a corner of the figure for the
        # apex so it does not collide with the title.
        if pos is A:
            ax.text(pos[0] + 1.1, pos[1] + 0.0, body,
                    ha="left", va="center", fontsize=9.5, color=C_DARK)
        elif pos is B:
            ax.text(pos[0] - 0.8, pos[1] - 1.25, body,
                    ha="center", va="top", fontsize=9.5, color=C_DARK)
        else:
            ax.text(pos[0] + 0.8, pos[1] - 1.25, body,
                    ha="center", va="top", fontsize=9.5, color=C_DARK)

    # Edge labels (themes that bridge two pillars).
    def midpt(p, q): return (p + q) / 2.0
    edges = [
        (A, B, "spectral theory\nlinks shape to stability"),
        (A, C, "sketching: keep\ngeometry at scale"),
        (B, C, "low-precision\narithmetic"),
    ]
    for p, q, label in edges:
        m = midpt(p, q)
        # nudge outward
        n_vec = np.array([-(q - p)[1], (q - p)[0]])
        n_vec = n_vec / (np.linalg.norm(n_vec) + 1e-12)
        # choose direction away from centroid
        if np.dot(m - centroid, n_vec) < 0:
            n_vec = -n_vec
        m_out = m + 0.7 * n_vec
        ax.text(m_out[0], m_out[1], label,
                ha="center", va="center", fontsize=8.5,
                color=C_DARK, style="italic",
                bbox=dict(facecolor="white", edgecolor=C_GRAY,
                          boxstyle="round,pad=0.25", alpha=0.9))

    ax.set_xlim(-1.5, 11.5)
    ax.set_ylim(-0.6, 10.4)
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_aspect("equal")
    ax.set_title(
        "The recurring triangle of the series:\ngeometry, numerics, computation",
        fontsize=13, color=C_DARK,
    )
    for s in ax.spines.values():
        s.set_visible(False)
    ax.grid(False)

    save(fig, "fig7_three_pillars")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    fig1_concept_map()
    fig2_quantum_computing()
    fig3_tensor_networks()
    fig4_lie_rotations()
    fig5_random_to_free()
    fig6_persistence()
    fig7_three_pillars()
    print("All figures generated for chapter 18.")


if __name__ == "__main__":
    main()
